# setup.py  – build + “clean” helper for accel_cholesky
from setuptools import setup, Extension
from Cython.Build import cythonize
from distutils.command.clean import clean as _clean
import pathlib
import numpy as np
import shutil

# ---------- extension ----------------------------------------------------
ext = Extension(
    "accel_cholesky",
    sources=["accel_cholesky.pyx", "mps_cholesky.m"],
    include_dirs=[np.get_include()],
    extra_compile_args=["-fobjc-arc"],
    extra_link_args=["-framework", "Accelerate"],
    language="c",
)

# ---------- custom clean -------------------------------------------------
class clean(_clean):
    description = "remove build artifacts generated by Cython / setuptools"

    def run(self):
        _clean.run(self)

        # generated C file
        c_file = pathlib.Path("accel_cholesky.c")
        if c_file.exists():
            print(f"removing {c_file}")
            c_file.unlink()

        # build/ directory
        build_dir = pathlib.Path("build")
        if build_dir.is_dir():
            print(f"removing {build_dir}")
            shutil.rmtree(build_dir)

        # any compiled .so (or .dylib) left in the project root
        for so_file in pathlib.Path(".").glob("*.so"):
            print(f"removing {so_file}")
            so_file.unlink()
        for dylib_file in pathlib.Path(".").glob("*.dylib"):
            print(f"removing {dylib_file}")
            dylib_file.unlink()

# ---------- setup --------------------------------------------------------
setup(
    name="accel_cholesky",
    ext_modules=cythonize([ext], language_level="3"),
    cmdclass={"clean": clean},
    zip_safe=False,
)
